### get alls books
GET {{baseURL}}books
Content-Type: application/json

### get alls books
GET {{baseURL}}books/search/findByTitleContaining?title=guru&page=0&size=5
Content-Type: application/json

### get by category
GET {{baseURL}}books/search/findByCategory?category=fe&page=0&size=5
Content-Type: application/json

### get all reviews
GET {{baseURL}}reviews
Content-Type: application/json

### get review by book id
GET {{baseURL}}reviews/search/findByBookId?bookId=2
Content-Type: application/json

### checkout test
PUT {{baseURL}}books/secure/checkout?bookId=1

### already checked out test
GET {{baseURL}}books/secure/ischeckedout/byuser?bookId=1

### get currentloans/count
GET {{baseURL}}books/secure/currentloans/count
