### get alls books
GET {{baseURL}}books
Content-Type: application/json

### get alls books
GET {{baseURL}}books/search/findByTitleContaining?title=guru&page=0&size=5
Content-Type: application/json

### get by category
GET {{baseURL}}books/search/findByCategory?category=fe&page=0&size=5
Content-Type: application/json

### get all reviews
GET {{baseURL}}reviews
Content-Type: application/json

### get review by book id
GET {{baseURL}}reviews/search/findByBookId?bookId=2
Content-Type: application/json

### checkout test
PUT {{baseURL}}books/secure/checkout?bookId=1

### already checked out test
GET {{baseURL}}books/secure/ischeckedout/byuser?bookId=1
Authorization: Bearer eyJraWQiOiIwZUw4SmJJUVBROUZzYkltWXg0SHhNTFpldG1qd0Z3NFl6clVVVk9sdW1JIiwiYWxnIjoiUlMyNTYifQ.eyJ2ZXIiOjEsImp0aSI6IkFULnNYeDZla0xhRmRzSkRHakhLTkVHMk5tMUtxaDBMWDVqcmJ4eDBDc1VRQkkiLCJpc3MiOiJodHRwczovL2Rldi04MzM4NTk0Ny5va3RhLmNvbS9vYXV0aDIvZGVmYXVsdCIsImF1ZCI6ImFwaTovL2RlZmF1bHQiLCJpYXQiOjE2NzUyOTg1NTcsImV4cCI6MTY3NTMwMjE1NywiY2lkIjoiMG9hODU3dXhwYmQ1NjlqelY1ZDciLCJ1aWQiOiIwMHU4NTdqaGc2UWZPVTN5TTVkNyIsInNjcCI6WyJwcm9maWxlIiwiZW1haWwiLCJvcGVuaWQiXSwiYXV0aF90aW1lIjoxNjc1Mjk4NTU2LCJzdWIiOiJ0ZXN0QGVtYWlsLmNvbSJ9.ZpkAl09LA4wQFh5OB64qbbLEZk9JTn1ALC_b9fxS0iYHiKEXwpNrni3M7tbWSUZFRvnBZbPkfTsHbPbC3LvP7v_OzHn5sHxbJ-OxIZYDv_KcJLNSsnElaUbYrsdsa5uA4E8TOfwf3QuqubUfy9SxpB5wNLMZClDIJbF1U8e6LfRawTR8sTOZ_YBCOHU5OpkGUL9CB0jWE3VgH6zzsUdgfkhqAmayfrSEA-lbS5KMwLvZO4GnPgmfxbeCcDLn7K650W5Q4qedn7efEVMaUI9TkW8nzlVYMjolIJBe7lLU5ug26FQ3eOT55fOmtIq40r6VTEwDSg9aGy8csBo77H_buw
Content-Type: application/json

### get currentloans/count
GET {{baseURL}}books/secure/currentloans/count
Authorization: Bearer eyJraWQiOiIwZUw4SmJJUVBROUZzYkltWXg0SHhNTFpldG1qd0Z3NFl6clVVVk9sdW1JIiwiYWxnIjoiUlMyNTYifQ.eyJ2ZXIiOjEsImp0aSI6IkFULnNYeDZla0xhRmRzSkRHakhLTkVHMk5tMUtxaDBMWDVqcmJ4eDBDc1VRQkkiLCJpc3MiOiJodHRwczovL2Rldi04MzM4NTk0Ny5va3RhLmNvbS9vYXV0aDIvZGVmYXVsdCIsImF1ZCI6ImFwaTovL2RlZmF1bHQiLCJpYXQiOjE2NzUyOTg1NTcsImV4cCI6MTY3NTMwMjE1NywiY2lkIjoiMG9hODU3dXhwYmQ1NjlqelY1ZDciLCJ1aWQiOiIwMHU4NTdqaGc2UWZPVTN5TTVkNyIsInNjcCI6WyJwcm9maWxlIiwiZW1haWwiLCJvcGVuaWQiXSwiYXV0aF90aW1lIjoxNjc1Mjk4NTU2LCJzdWIiOiJ0ZXN0QGVtYWlsLmNvbSJ9.ZpkAl09LA4wQFh5OB64qbbLEZk9JTn1ALC_b9fxS0iYHiKEXwpNrni3M7tbWSUZFRvnBZbPkfTsHbPbC3LvP7v_OzHn5sHxbJ-OxIZYDv_KcJLNSsnElaUbYrsdsa5uA4E8TOfwf3QuqubUfy9SxpB5wNLMZClDIJbF1U8e6LfRawTR8sTOZ_YBCOHU5OpkGUL9CB0jWE3VgH6zzsUdgfkhqAmayfrSEA-lbS5KMwLvZO4GnPgmfxbeCcDLn7K650W5Q4qedn7efEVMaUI9TkW8nzlVYMjolIJBe7lLU5ug26FQ3eOT55fOmtIq40r6VTEwDSg9aGy8csBo77H_buw
Content-Type: application/json

### post review
POST {{baseURL}}reviews/secure
Authorization: Bearer eyJraWQiOiIwZUw4SmJJUVBROUZzYkltWXg0SHhNTFpldG1qd0Z3NFl6clVVVk9sdW1JIiwiYWxnIjoiUlMyNTYifQ.eyJ2ZXIiOjEsImp0aSI6IkFULnNYeDZla0xhRmRzSkRHakhLTkVHMk5tMUtxaDBMWDVqcmJ4eDBDc1VRQkkiLCJpc3MiOiJodHRwczovL2Rldi04MzM4NTk0Ny5va3RhLmNvbS9vYXV0aDIvZGVmYXVsdCIsImF1ZCI6ImFwaTovL2RlZmF1bHQiLCJpYXQiOjE2NzUyOTg1NTcsImV4cCI6MTY3NTMwMjE1NywiY2lkIjoiMG9hODU3dXhwYmQ1NjlqelY1ZDciLCJ1aWQiOiIwMHU4NTdqaGc2UWZPVTN5TTVkNyIsInNjcCI6WyJwcm9maWxlIiwiZW1haWwiLCJvcGVuaWQiXSwiYXV0aF90aW1lIjoxNjc1Mjk4NTU2LCJzdWIiOiJ0ZXN0QGVtYWlsLmNvbSJ9.ZpkAl09LA4wQFh5OB64qbbLEZk9JTn1ALC_b9fxS0iYHiKEXwpNrni3M7tbWSUZFRvnBZbPkfTsHbPbC3LvP7v_OzHn5sHxbJ-OxIZYDv_KcJLNSsnElaUbYrsdsa5uA4E8TOfwf3QuqubUfy9SxpB5wNLMZClDIJbF1U8e6LfRawTR8sTOZ_YBCOHU5OpkGUL9CB0jWE3VgH6zzsUdgfkhqAmayfrSEA-lbS5KMwLvZO4GnPgmfxbeCcDLn7K650W5Q4qedn7efEVMaUI9TkW8nzlVYMjolIJBe7lLU5ug26FQ3eOT55fOmtIq40r6VTEwDSg9aGy8csBo77H_buw
Content-Type: application/json

{
  "rating": 5,
  "bookId": 1,
  "reviewDescription": "Very good book!"
}

###
GET {{baseURL}}/reviews/secure/user/book/?bookId=1

###
GET {{baseURL}}/books/secure/currentloans
Authorization: Bearer eyJraWQiOiIwZUw4SmJJUVBROUZzYkltWXg0SHhNTFpldG1qd0Z3NFl6clVVVk9sdW1JIiwiYWxnIjoiUlMyNTYifQ.eyJ2ZXIiOjEsImp0aSI6IkFULjhaV3FCVVV5N2xyVlZSeWs3NHlDY0xEN0VIYjdybU5NWVFfb3VQV0lRaUEiLCJpc3MiOiJodHRwczovL2Rldi04MzM4NTk0Ny5va3RhLmNvbS9vYXV0aDIvZGVmYXVsdCIsImF1ZCI6ImFwaTovL2RlZmF1bHQiLCJpYXQiOjE2NzU5NjA0MjcsImV4cCI6MTY3NTk2NDAyNywiY2lkIjoiMG9hODU3dXhwYmQ1NjlqelY1ZDciLCJ1aWQiOiIwMHU4NTdqaGc2UWZPVTN5TTVkNyIsInNjcCI6WyJvcGVuaWQiLCJlbWFpbCIsInByb2ZpbGUiXSwiYXV0aF90aW1lIjoxNjc1OTYwNDI1LCJzdWIiOiJ0ZXN0QGVtYWlsLmNvbSJ9.FQE92VbvAorZ5CVuzemlhHuTGI4msQtzRjO9BN1I5gkYachp_gQkNFmTDuaDGVfqh2TRxIzlIG_vlE23-uuy-o-teUOt8W6Qbop7GTnsFtlYVcdclJY8lYpE7KZJQb8eV38S_yr81V5NYYD02eF07xvxj-DIKy7hLrIayRSXuvu6XbIbcX7QicNq0R-DwQK_ktNCTJJ5_giN1jiNzZhrfF-ACPRdIaxqC8mjeWC9WbboMB1LYCJnPqgcmN80Q987HPNmzKrhiKp6WgTJ6xWIaTEIKGoQOnWV2PLE1_xW9CbRP03IlclW2BArc7NMpCg9rC2sWyWYRL5xUD4_Iy-W-w
Content-Type: application/json